Formatting for object descriptions.
DarviL82/Lanat pull request #3
Opened 2023-02-27 20:28 UTC by DarviL82

Allow descriptions of objects, such as Argument's or Command's to have richer information. At the moment, when printing the description on the help view, both the description specified to the argument and the one of the argument type are shown.
This is great, but it would be neat to allow more customization, such as being able to specify formatting semantics, like `{@link args.arg1}` or `{@link cmds.mySubcmd1}`.

## Example:
```java
Argument.create("test").description("Interesting argument. See also {@link args.arg1}.")
```

When being printed on the help, this is what would be shown:
```
--test:
   Interesting argument. See also --arg1.
```
`--arg1` would be shown with the color that represents it. And also, if it had multiple names, these would be shown like `--arg1/argument1`. Basically the argument representation that is normally shown for each argument.

2023-02-27 21:26 UTC, fadeoffical commented
You sure you want to pull into main?

2023-02-27 21:30 UTC, DarviL82 commented
Nah it'll be merged into dev. Forgot to change that.

2023-03-08 22:18 UTC, fadeoffical requested changes
Lgtm! except the two finals.

2023-03-08 22:18 UTC, fadeoffical commented on src/main/java/lanat/helpRepresentation/ArgumentRepr.java
> +	public static @Nullable String getDescription(final @NotNull Argument<?, ?> arg) {
Is the final modifier really needed?
```suggestion
	public static @Nullable String getDescription(@NotNull Argument<?, ?> arg) {
```

2023-03-08 22:18 UTC, fadeoffical commented on src/main/java/lanat/helpRepresentation/ArgumentRepr.java
> +	static String getDescriptions(final @NotNull List<@NotNull Argument<?, ?>> arguments) {
Is the final modifier really needed?
```suggestion
	static String getDescriptions(@NotNull List<@NotNull Argument<?, ?>> arguments) {
```

2023-03-09 02:12 UTC, merged